name: advent_of_code_2023
description: My solutions to Advent of Code 2023! ^.^
version: 1.0.0
repository: https://github.com/francisconicola/advent_of_code_2023

environment:
  sdk: ^3.1.2

dependencies:
  args: ^2.4.2
  characters: ^1.3.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
